#!/bin/bash

export DESKTOP_CORE_NAME="orbstack"
export DESKTOP_CORE_BIN_NAME="$DESKTOP_CORE_NAME"
export DESKTOP_CORE_VERSION=v1.0.0_16230
export DESKTOP_CORE_MD5SUM=5eeac1c71caff672e99d3f4180f09233
export DESKTOP_CORE_ORG="orbstack"

export DESKTOP_CORE_RELEASE_DOWNLOAD="https://cdn-updates.orbstack.dev"
